class StudentConstant:

    def __init__(self):
        pass

    STOPWORDS = [
        'BEATRIZ',
        'ANNA',
        'AMORIM',
        'SANTOS',
        'BIANCA',
        'CHALON',
        'CLEONICE', 'JULIANA',
        'DHESLAYNE', 'THIPANY',
        'IRIS',
        'BARRETO',
        'JANÚARIO',
        'JANUARIO',
        'EMANOEL',
        'EMANUEL', 'MESSIAS',
        'JOSE', 'JOSÉ', 'DINIZ',
        'EVELYNN', 'VATYCIANI',
        'GABRIEL', 'ERMINIO', 'ERMÍNIO', 'SILVA',
        'GILSON', 'LISBOA', 'FERREIRA',
        'ISAÍLDA', 'ISAILDA',
        'JULIA', 'MARLEY',
        'LAIS', 'ROSILENE', 'FREITAS',
        'JOSIANE', 'MARIA', 'SANTANA',
        'LEANDRO', 'LEMOS',
        'MARINA', 'MILENA', 'LIMA', 'SANTOS',
        'MARIA', 'MADALENA', 'BALDEZ', 'SILVA',
        'MARIANA', 'FRAGA', 'OLIVEIRA', 'GALVÃO',
        'MELINA', 'EMILLE', 'NUNES', 'GENÚ',
        'RODRIGO', 'LEANDRO', 'LIRA',
        'VINICIUS', 'GONZALO', 'GONÇALO',
        'JUVENAL', 'DAMASCENO',
        'JUVE', 'AMARAL',
        'CONGREGAÇÃO DE SANTA DOROTEIA DO BRASIL',
        'ISAILDA FERREIRA DA SILVA',
        'DINABEL',
        'ALVES',
        'CIRNE',
        'VILAS-BOAS',
        'VILAS BOAS',
        'CURSO DE CIÊNCIAS BIOLÓGICAS',
        'FACULDADE FRASINETTI DO RECIFE',
        'FACULDADE FRASSINETTI DO RECIFE',
        'FACULDADE FRASSINETI DO RECIFE',
        'FRASINETTI',
        'FACULDADE',
        'FAFIRE',
        'PE',
        'AV.',
        'CONDE DA BOA VISTA',
        'BOA VISTA',
        'AMARAL',
        'JUNIOR',
        'FILHO',
        'GOMES',
        'RABELO',
        'MOREIRA',
        'NASCIMENTO',
        'METODOLOGIA DO ENSINO DE CIÊNCIAS E BIOLOGIA',
        'MOABE',
        'CLEMENTE',
        'SANTOS',
        'CURSO DE CIÊNCIAS BIOLÓGICAS',
        'CURSO DE CIENCIAS BIOLOGICAS',
        'ALUNA:',
        'ALUNA',
        'ALUNO',
        'ALUNO:',
        'JÚLIA',
        'NASCIMENTO',
        'MARINA MILENA LIMA',
        'FONE: (81) 2122-3500',
        'FAX: (81)3423-3066',
        'DEPARTAMENTO DE CIÊNCIAS BIOLÓGICAS',
        'AV. CONDE DA BOA VISTA, 921 - BOA VISTA, - PE, 50060-002',
        '50060-002',
        'BIOLOGIA DA CONSERVAÇÃO',
        'QUAIS OS TERMOS NOVOS ENCONTRADOS NO TEXTO? BUSQUE O SIGNIFICADO E DEFINIÇÃO DOS TERMOS QUE VOCÊ NÃO CONHECE',
        'O QUE VOCÊ DESTACARIA NO ARTIGO PARA COMPARTILHAR COM SEUS COLEGAS',
        'OS DOIS EXEMPLOS ACIMA ILUSTRAM O QUE ACONTECE QUANDO DUAS ESPÉCIES COMPETEM. EXPLIQUE O QUE LEVA A CADA UM DESTES PROCESSOS',
        'VOCÊ ENTENDE COMO SE TRABALHAR COM A INTERDISCIPLINARIDADE E TRANSVERSALIDADE? ELABORE UM TEXTO E COMPARTILHE A SUA COMPREENSÃO',
        'RELATORIO DO TEXTO: “PORQUE APRENDER E ENSINAR CIÊNCIAS NATURAIS',
        'CAMPUS – /PE',
        'QUAIS AS SUAS DÚVIDAS?',
        'GRADUAÇÃO EM CIÊNCIAS BIOLÓGICAS',
        'BACHARELADO',
        'LICENCIATURA',
        'ECOLOGIA DE POPULAÇÕES E COMUNIDADES',
        'DOCENTE:',
        'DISCENTE:',
        'DISCIPLINA:',
        '(81)3423-3066',
        '2019',
        '2019.1',
        '2018',
        '2018.1',
        '2018.2',
        '2019.2'
        ]


